config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :days, only: [:index, :show, :edit, :update] do
    collection do
      get ':year/:month/:date' => 'my_calendar#show', :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }
    end
  end
  get '/mood/stats', to: 'stats#mood_stats', as: 'mood_stats'
  get '/pain/stats', to: 'stats#pain_stats', as: 'pain_stats'
  get '/exercise/stats', to: 'stats#exercise_stats', as: 'exercise_stats'
  get '/sleep/stats', to: 'stats#sleep_stats', as: 'sleep_stats'


  resources :moods, only: [:new, :create, :destroy]
  resources :pains, only: [:new, :create, :destroy]
  resources :exercises, only: [:new, :create, :destroy]
  resources :sleeps, only: [:new, :create, :destroy]
  resources :stats, only: [:all_stats]
  resources :journals do
    collection do
      get 'new_video'
      post 'create_video'
    end
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<div class="our-navbar">
  <%= link_to root_path do  %>
    <i class="fas fa-home" id="home"></i>
  <% end %>
  <%= link_to days_path do  %>
    <i class="far fa-calendar-alt"></i>
  <% end %>
  <%= link_to new_mood_path do  %>
    <!-- <i class="fas fa-plus" id="plus"></i> -->
    <!-- <i class="far fa-plus-square" id="plus"></i> -->
    <i class="fas fa-plus-circle" id="plus"></i>
  <% end %>
  <%= link_to journals_path do  %>
  <i class="fas fa-book book-nav"></i>
  <% end %>
  <%= link_to mood_stats_path do  %>
    <i class="far fa-chart-bar"></i>
  <% end %>
</div>

app/views/shared/_optionswipe.html.erb
<div class="option-swipe" data-controller="<%= params[:controller] %>">
  <span class="tab moods"  ><%= link_to "Mood", new_mood_path %></span>
  <span class="tab pains"><%= link_to "Pain", new_pain_path %></span>
  <span class="tab sleeps"><%= link_to "Sleep", new_sleep_path %></span>
  <!-- <span class="tab"><i class="fas fa-chevron-right" id="arrow"></i></span> -->
  <span class="tab exercises"><%= link_to "Exercise", new_exercise_path %></span>
</div>

<!-- find out the params controller -->
<!--  in js we want to find correct tab class that is same name as controller -->
<!-- params[:controller"] = "moods" <span class="moods"></span> -->
<!-- find span with class of params[:controller] -->
<script>
  const paramsControllerName = document.querySelector('.option-swipe').dataset.controller

  const tabs = document.querySelectorAll('.tab');

  tabs.forEach(tab => {
    tab.classList.remove('actives');
    if(tab.classList.contains(paramsControllerName)){
      tab.classList.add('actives')
    }
  })
</script>

app/views/shared/_show_events.html.erb
<div class="show-box">
  <% if day.nil? %>
  <span class="show-info">


  <!--    <span> <i class="fas fa-spinner"></i> No information entered for this day</span></span> -->

   <% else %>
   <div class="d-flex flex-row-reverse box-date"><%= day.date.strftime("%A, %b %d") %>

   </div>
   <% day.all_events_today(current_user).each do |event| %>
   <div class="d-flex justify-content-start align-items-center">
    <% if event.is_a?(Mood) %>
    <span> <div class="mood-event-show"> <% @moods.each do |mood| %>
      <%= link_to "X", mood_path(mood),
      method: :delete,
      data: { confirm: "Are you sure?" }, class: "delete-but" %>

      <% end %></div></span>
      <span class="show-info">
        <span id="mood-name"><%= event.class %></span>
        <span id="mood-info"> <%= event.feeling %></span></span>


        <% elsif event.is_a?(Exercise) %>
        <span><div class="exercise-event-show"><% @exercises.each do |exercise| %>
         <%= link_to "X", exercise_path(exercise),
         method: :delete,
         data: { confirm: "Are you sure?" }, class: "delete-but-x" %>

         <% end %></div></span>
         <span class="show-info">
           <span id="ex-name"> <%= event.class %></span>
           <span id="ex-info"> <%= event.time %> minutes</span></span>

           <% elsif event.is_a?(Pain) %>
           <span><div class="pain-event-show">
             <% @pains.each do |pain| %>
             <%= link_to "X", pain_path(pain),
             method: :delete,
             data: { confirm: "Are you sure?" }, class: "delete-but-p" %>

             <% end %></div></span>
             <span class="show-info">
              <span id="pain-name"><%= event.class %></span>
              <span id="pain-info"> <%= event.symptom %></span></span>

              <% elsif event.is_a?(Sleep) %>
              <span><div class="sleep-event-show">
                <% @sleeps.each do |sleep| %>
                <%= link_to "X", sleep_path(sleep),
                method: :delete,
                data: { confirm: "Are you sure?" }, class: "delete-but-s" %>
                <% end %></div></span>
                <span class="show-info">
                  <span id="sleep-name"><%= event.class %></span>
                  <span id="sleep-info"> <%= event.hours %> hours</span></span>
                  <% end %>
                </div>
                <% end %>
                <% end %>



              </div>

            </div>

app/views/shared/_statswipe.html.erb
<div class="option-swipe" data-action="<%= params[:action] %>">
  <%#raise %>
  <span class="tab moods mood_stats"  ><%= link_to "Mood", mood_stats_path %></span>
  <span class="tab pains pain_stats"><%= link_to "Pain", pain_stats_path %></span>
  <span class="tab sleeps sleep_stats"><%= link_to "Sleep", sleep_stats_path %></span>
  <!-- <span class="tab"><i class="fas fa-chevron-right" id="arrow"></i></span> -->
  <span class="tab exercises exercise_stats"><%= link_to "Exercise", exercise_stats_path %></span>
</div>

<!-- find out the params controller -->
<!--  in js we want to find correct tab class that is same name as controller -->
<!-- params[:controller"] = "moods" <span class="moods"></span> -->
<!-- find span with class of params[:controller] -->
<script>
  const paramsControllerName = document.querySelector('.option-swipe').dataset.action

  const tabs = document.querySelectorAll('.tab');

  tabs.forEach(tab => {
    tab.classList.remove('actives');
    if(tab.classList.contains(paramsControllerName)){
      tab.classList.add('actives')
    }
  })
</script>