config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :days, only: [:index, :show, :edit, :update] do
    collection do
      get ':year/:month/:date' => 'my_calendar#show', :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }
    end
  end
  get '/mood/stats', to: 'stats#mood_stats', as: 'mood_stats'
  get '/pain/stats', to: 'stats#pain_stats', as: 'pain_stats'
  get '/exercise/stats', to: 'stats#exercise_stats', as: 'exercise_stats'
  get '/sleep/stats', to: 'stats#sleep_stats', as: 'sleep_stats'


  resources :moods, only: [:new, :create, :destroy]
  resources :pains, only: [:new, :create, :destroy]
  resources :exercises, only: [:new, :create, :destroy]
  resources :sleeps, only: [:new, :create, :destroy]
  resources :stats, only: [:all_stats]
  resources :journals do
    collection do
      get 'new_video'
      post 'create_video'
    end
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/journal.rb
class Journal < ApplicationRecord
  mount_uploader :video, VideoUploader
  belongs_to :user


end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

  before_action :set_journal, only: [:show, :edit, :destroy, :update]
  def index
    @journals = policy_scope(Journal).order(created_at: :desc)
    @journal = Journal.new
  end

  def show
    # @journal = Journal.find(params[:id])
      authorize @journal
  end

  def new
    @journal = Journal.new
    authorize @journal

  end

  def create
    @journal = Journal.new(journal_params)
        @journal.user = current_user

      authorize @journal
    if @journal.save

      redirect_to journals_path
    else
      render :new
    end
  end

  def edit
# authorize @journal
  end

  def update
# authorize @journal
    if @journal.update(journal_params)
      redirect_to @journal, notice: 'Journal was successfully updated.'
    else
      render :edit
    end
  end
  def new_video
    @journal = Journal.new
    authorize @journal
  end
  def create_video
    @journal = Journal.new(video_params)
    @journal.user = current_user
    # @journal.title = DateTime.now
    @journal.title = "Video Entry"
    authorize @journal

    if @journal.video.nil?
      redirect_to journals_path, alert: "No Video Found"
    elsif @journal.save
    redirect_to journals_path, notice: "Journal Video was successfully created."
    else
      render :new
    end
  end

  def destroy
    @journal.destroy
    redirect_to journals_path
  end

  private

  def journal_params
    params.require(:journal).permit(:title, :text)
  end

  def video_params
    params.require(:journal).permit(:title,:video, :video_cache)
  end

  def set_journal
      @journal = Journal.find(params[:id])
      authorize @journal
    end
end

app/views/journals/_new_text.html.erb
<div class="text-entry-2">
  <p><i class="far fa-file-alt text-icon"></i></p>
  </div>
  <div class="journal-info">
    <p class="card-date"> <%= journal.created_at.strftime("%A, %B %e, %Y") %></p>
    <h4 ><%= journal.title.first(12) %></h4>
    <p ><%= journal.text.truncate_words(6) %></p>
   </div>

   <i class='fas fa-chevron-right show-fas'></i>

app/views/journals/_new_video.html.erb
<div class="video-entry-2">
     <p><i class="fas fa-video video-icon"></i></p>
  </div>
  <div class="journal-info">
    <p class="card-date"> <%= journal.created_at.strftime("%A, %B %e, %Y") %></p>
    <h4> Video Entry</h4>
    <p> <%= journal.created_at.strftime("%I:%M %p") %></p>
   </div>
   <i class='fas fa-chevron-right show-fas'></i>

app/views/journals/edit.html.erb
<body class='journal'>
  <h5 class="journal-date"><%= Date.today.strftime("%A, %B %eth, %Y") %></h5>

<%= simple_form_for @journal do |f| %>

  <%= f.input :title, label:false, placeholder: "Add a title", class: "journal_title" %>


  <%= f.input :text, as: :text, label: false, placeholder: "Tap here to start typing", class: "journal_text" %>

  <%= f.button :submit, "Finish Editing", class: "btn-success btn-block journal-btn" %>
<% end %>
</body>

app/views/journals/index.html.erb
<div class="journal-back">


<h3 class="journal-header">Journal</h3>


  <!-- <div class="journal-icons"> -->
    <h5 class="inout-method">Choose your input method:</h5>
    <div class="d-flex justify-content-around">
     <%= link_to new_journal_path do  %>
      <p class="btn btn-danger text-button">Add Text</p>

  <% end %>
   <%= link_to new_video_journals_path do  %>

      <p class="btn btn-danger video-button">Record Video</p>

    <% end %>
    </div>
<!-- </div> -->




<div class="journal-border">
    <%@journals.each do |journal| %>
    <%= link_to journal_path(journal), class:"journal-show" do %>

  <% if journal.text %>
    <%= render 'new_text', journal: journal %>
    <% else %>
    <%= render 'new_video', journal: journal %>
    <% end %>


   <!-- </div> -->
  <% end %>
      <% end %>
      </div>



</div>

app/views/journals/new.html.erb
<body class='journal'>
  <h5 class="journal-date"><%= Date.today.strftime("%A, %B %eth, %Y") %></h5>

<%= simple_form_for @journal do |f| %>

  <%= f.input :title, label:false, placeholder: "Add a title", class: "journal_title" %>


  <%= f.input :text, as: :text, label: false, placeholder: "Tap here to start typing", class: "journal_text" %>

  <%= f.button :submit, "Create", class: "btn-success btn-block journal-btn" %>
<% end %>
</body>

app/views/journals/new_video.html.erb
<div class="new-vid-back">
  <h3 class="video-journal">Video Journal</h3>
  <div class="d-flex justify-content-center align-items-center flex-column video-container-flex">
  <h5 class="add-entry">Tap to add an entry</h5>
  <%= simple_form_for(@journal, url: create_video_journals_path, method: :post) do |f| %>
    <div class="position-icon">
    <%= f.input :video, input_html: { class: 'd-none' }, label_html: { class: 'upload-video button-add-icon'}, label: 'Record' %>
    <i class="fas fa-video video-icon-new"></i>
    <%= f.input :video_cache, as: :hidden %>
    </div>
    </div>
    <%= f.button :submit, "Done", class: "btn-block video-done "%>
  <% end %>
</div>

app/views/journals/show.html.erb
<div class="show-background">

<div class="journal-options d-flex bd-highlight mb-3 align-items-center">
  <%= link_to journals_path do %>
<i class="far fa-arrow-alt-circle-left back-but mr-auto p-2 bd-highlight"></i>
<% end %>
  <h6 class="show-date mr-auto p-2 bd-highlight"><%= @journal.created_at.strftime("%A, %B %e, %Y") %></h6>

<% if @journal.text %>

<%= link_to edit_journal_path(@journal) do %>
<i class="fas fa-pencil-alt journal-ed p-2 bd-highlight"></i>
<% end %>
<% end %>

<%= link_to journal_path(@journal), method: :delete,
      data: { confirm: "Are you sure?" } do %>
<i class="fas fa-trash journal-del p-2 bd-highlight"></i>
<% end %>


</div>
<% if @journal.text %>
<h5 class="show-title"><%= @journal.title %></h5>

<p class="show-text"><%= @journal.text %></p>

<% else %>
<%#= cl_video_tag @journal.video_url.to_s, :controls  => true, :poster => true %>

<video controls autoplay class="video-player">
  <source src="<%= @journal.video_url.to_s  %>" type="video/mp4">
</video>

<% end %>
</div>